package(default_visibility = ["//visibility:public"])

filegroup(
    name = "map_xiaolan_big_loop",
    testonly = True,
    srcs = glob([
        "demo/**",
    ]),
)

filegroup(
    name = "map_xiaolan_loop",
    testonly = True,
    srcs = glob([
        "demo/**",
    ]),
)
